jstorm-ui/src/main/java/com/alibaba/jstorm/ui/model/UINettyMetric.java
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.jstorm.ui.model;

import com.alibaba.jstorm.metric.MetricDef;

/**
 * @author Jark (wuchong.wc@alibaba-inc.com)
 */
public class UINettyMetric extends UIBasicMetric {
    private String connection;
    private String fromWorker;
    private String toWorker;
    private boolean isFrom = false;
    private boolean isTo = false;

    public static final String[] HEAD = {MetricDef.NETTY_SRV_MSG_TRANS_TIME};

    public UINettyMetric(String host, String connection) {
        this.connection = connection;
        this.fromWorker = connection.split("->")[0];
        this.toWorker = connection.split("->")[1];
        if (fromWorker.contains(host)) {
            isFrom = true;
        }
        if (toWorker.contains(host)) {
            isTo = true;
        }
    }


    public String getConnection() {
        return connection;
    }

    public String getFromWorker() {
        return fromWorker;
    }

    public String getToWorker() {
        return toWorker;
    }

    public boolean isFrom() {
        return isFrom;
    }

    public boolean isTo() {
        return isTo;
    }
}

jstorm-ui/src/main/java/com/alibaba/jstorm/ui/model/UITaskMetric.java
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.jstorm.ui.model;

import com.alibaba.jstorm.metric.MetricDef;
import com.alibaba.jstorm.ui.utils.UIMetricUtils;
import com.alibaba.jstorm.utils.JStormUtils;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.*;

/**
 * @author Jark (wuchong.wc@alibaba-inc.com)
 */
public class UITaskMetric extends UIComponentMetric {

    private String taskId;

    private static List<String> METRIC_QUEUE = Arrays.asList(MetricDef.EXECUTE_QUEUE,
            MetricDef.DESERIALIZE_QUEUE, MetricDef.SERIALIZE_QUEUE, MetricDef.CONTROL_QUEUE);

    private static final String FORMAT = "##0.00";

    public static final String[] HEAD = {MetricDef.EMMITTED_NUM, MetricDef.ACKED_NUM, MetricDef.FAILED_NUM, MetricDef.SEND_TPS,
            MetricDef.RECV_TPS, MetricDef.PROCESS_LATENCY,  MetricDef.DESERIALIZE_TIME, MetricDef.SERIALIZE_TIME, MetricDef.EXECUTE_TIME,
            MetricDef.COLLECTOR_EMIT_TIME, MetricDef.ACKER_TIME, MetricDef.DESERIALIZE_QUEUE, MetricDef.SERIALIZE_QUEUE,
            MetricDef.EXECUTE_QUEUE, MetricDef.CONTROL_QUEUE};

    public UITaskMetric(String componentName, int taskId) {
        super(componentName);
        this.taskId = taskId+"";
    }


    public void mergeValue() {
        super.mergeValue();
        // the queue value should be displayed in percent
        for (String q : METRIC_QUEUE){
            if (metrics.containsKey(q)){
                metrics.put(q, UIMetricUtils.format(JStormUtils.parseDouble(metrics.get(q), 0) * 100, FORMAT));
            }
        }
        for (Map.Entry<String,String> entry : subMetrics.entrySet()){
            String metricName = entry.getKey().split("@")[0];
            String value = entry.getValue();
            if(METRIC_QUEUE.contains(metricName)){
                String v = UIMetricUtils.format(JStormUtils.parseDouble(value, 0)*100,FORMAT);
                subMetrics.put(entry.getKey(), v);
            }
        }
    }

    public String getTaskId() {
        return taskId;
    }

    @JsonIgnore
    @Override
    public List<ErrorEntity> getErrors() {
        return super.getErrors();
    }

    @JsonIgnore
    @Override
    public String getType() {
        return super.getType();
    }

    @JsonIgnore
    @Override
    public int getParallel() {
        return super.getParallel();
    }

    @JsonIgnore
    @Override
    public String getComponentName() {
        return super.getComponentName();
    }
}

jstorm-ui/src/main/java/com/alibaba/jstorm/ui/controller/ClusterController.java
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.jstorm.ui.controller;

import java.util.List;
import java.util.Map;

import backtype.storm.generated.*;
import com.alibaba.jstorm.metric.*;
import com.alibaba.jstorm.ui.model.*;
import com.alibaba.jstorm.ui.utils.UIMetricUtils;
import org.apache.commons.lang.StringEscapeUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.alibaba.jstorm.ui.utils.NimbusClientManager;
import com.alibaba.jstorm.ui.utils.UIUtils;
import com.alibaba.jstorm.utils.JStormUtils;

import backtype.storm.utils.NimbusClient;

/**
 * @author Jark (wuchong.wc@alibaba-inc.com)
 */
@Controller
public class ClusterController {

    private static final Logger LOG = LoggerFactory.getLogger(ClusterController.class);

    @RequestMapping(value = "/cluster", method = RequestMethod.GET)
    public String show(@RequestParam(value = "name", required = true) String name,
                       ModelMap model) {
        name = StringEscapeUtils.escapeHtml(name);
        long start = System.currentTimeMillis();
        NimbusClient client = null;
        try {
            client = NimbusClientManager.getNimbusClient(name);
            ClusterSummary clusterSummary = client.getClient().getClusterInfo();

            model.addAttribute("nimbus", UIUtils.getNimbusEntities(clusterSummary));
            model.addAttribute("topologies", UIUtils.getTopologyEntities(clusterSummary));
            model.addAttribute("supervisors", UIUtils.getSupervisorEntities(clusterSummary));

            model.addAttribute("zkServers", UIUtils.getZooKeeperEntities(name));

            List<MetricInfo> clusterMetrics = client.getClient().getMetrics(JStormMetrics.CLUSTER_METRIC_KEY,
                    MetaType.TOPOLOGY.getT());
            UISummaryMetric clusterData = UIMetricUtils.getSummaryMetrics(clusterMetrics, AsmWindow.M1_WINDOW);
            model.addAttribute("clusterData", clusterData);
            model.addAttribute("clusterHead", UIMetricUtils.sortHead(clusterData, UISummaryMetric.HEAD));


            //update cluster cache
            ClusterEntity ce = UIUtils.getClusterEntity(clusterSummary, name);
            model.addAttribute("cluster", ce);
            UIUtils.clustersCache.put(name, ce);
        } catch (Exception e) {
            NimbusClientManager.removeClient(name);
            LOG.error(e.getMessage(), e);
            UIUtils.addErrorAttribute(model, e);
        }

        //set nimbus port and supervisor port , if necessary
        model.addAttribute("nimbusPort", UIUtils.getNimbusPort(name));
        model.addAttribute("supervisorPort", UIUtils.getSupervisorPort(name));
        model.addAttribute("clusterName", name);
        model.addAttribute("page", "cluster");
        UIUtils.addTitleAttribute(model, "Cluster Summary");
        LOG.info("cluster page show cost:{}ms", System.currentTimeMillis() - start);
        return "cluster";
    }

}

jstorm-ui/src/main/java/com/alibaba/jstorm/ui/controller/ClustersController.java
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.jstorm.ui.controller;

import com.alibaba.jstorm.ui.model.ClusterEntity;
import com.alibaba.jstorm.ui.utils.UIUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.Collection;

/**
 * @author Jark (wuchong.wc@alibaba-inc.com)
 */
@Controller
public class ClustersController {

    private static final Logger LOG = LoggerFactory.getLogger(ClustersController.class);

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String show(ModelMap model) {
        UIUtils.readUiConfig();
        long start = System.currentTimeMillis();
        LOG.info("nimbus config: " + UIUtils.clusterConfig);
        Collection<ClusterEntity> clusterEntities = UIUtils.clustersCache.values();
        model.addAttribute("clusters", clusterEntities);
        model.addAttribute("nodes", getNodeCount(clusterEntities));
        UIUtils.addTitleAttribute(model, null);
        LOG.info("clusters page show cost:{}ms", System.currentTimeMillis() - start);
        return "clusters";
    }

    private int getNodeCount(Collection<ClusterEntity> clusterEntities){
        int count = 0;
        for (ClusterEntity c : clusterEntities){
            count += c.getSupervisors();
        }
        return count;
    }

}

jstorm-ui/src/main/java/com/alibaba/jstorm/ui/controller/ComponentController.java
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.jstorm.ui.controller;

import backtype.storm.generated.*;
import backtype.storm.utils.NimbusClient;
import com.alibaba.jstorm.cluster.Common;
import com.alibaba.jstorm.ui.model.UIComponentMetric;
import com.alibaba.jstorm.ui.model.TaskEntity;
import com.alibaba.jstorm.ui.model.UITaskMetric;
import com.alibaba.jstorm.ui.utils.NimbusClientManager;
import com.alibaba.jstorm.ui.utils.UIMetricUtils;
import com.alibaba.jstorm.ui.utils.UIUtils;
import com.alibaba.jstorm.utils.JStormUtils;
import org.apache.commons.lang.StringEscapeUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.*;

/**
 * @author Jark (wuchong.wc@alibaba-inc.com)
 */
@Controller
public class ComponentController {
    private static final Logger LOG = LoggerFactory.getLogger(ComponentController.class);

    @RequestMapping(value = "/component", method = RequestMethod.GET)
    public String show(@RequestParam(value = "cluster", required = true) String clusterName,
                       @RequestParam(value = "topology", required = true) String topology_id,
                       @RequestParam(value = "component", required = true) String component,
                       @RequestParam(value = "win", required = false) String win,
                       ModelMap model) {
        clusterName = StringEscapeUtils.escapeHtml(clusterName);
        topology_id = StringEscapeUtils.escapeHtml(topology_id);
        long start = System.currentTimeMillis();
        int window = UIUtils.parseWindow(win);
        UIUtils.addWindowAttribute(model, window);
        NimbusClient client = null;
        try {
            client = NimbusClientManager.getNimbusClient(clusterName);

            //get Component Metric
            TopologyInfo topologyInfo = client.getClient().getTopologyInfo(topology_id);
            MetricInfo componentMetrics = topologyInfo.get_metrics().get_componentMetric();
//            List<MetricInfo> componentMetrics = client.getClient().getMetrics(topology_id, MetaType.COMPONENT.getT());
            UIComponentMetric componentMetric = UIMetricUtils.getComponentMetric(componentMetrics, window,
                    component, topologyInfo.get_components());
            model.addAttribute("comp", componentMetric);
            model.addAttribute("compHead", UIMetricUtils.sortHead(componentMetric, UIComponentMetric.HEAD));

            //get Task Stat
            model.addAttribute("tasks", UIUtils.getTaskEntities(topologyInfo, component));

            //get Task metrics
//            MetricInfo taskMetrics = topologyInfo.get_metrics().get_taskMetric();
            MetricInfo taskMetrics = client.getClient().getTaskMetrics(topology_id, component);
//            System.out.println("taskMetrics:" + taskMetrics);
            List<UITaskMetric> taskData = UIMetricUtils.getTaskMetrics(taskMetrics, component, window);
            model.addAttribute("taskData", taskData);
            model.addAttribute("taskHead", UIMetricUtils.sortHead(taskData, UITaskMetric.HEAD));

        } catch (NotAliveException nae) {
            model.addAttribute("flush", String.format("The topology: %s is dead.", topology_id));
        } catch (Exception e) {
            NimbusClientManager.removeClient(clusterName);
            LOG.error(e.getMessage(), e);
            UIUtils.addErrorAttribute(model, e);
        }

        // page information
        model.addAttribute("clusterName", clusterName);
        model.addAttribute("topologyId", topology_id);
        model.addAttribute("compName", component);
        model.addAttribute("page", "component");
        model.addAttribute("supervisorPort", UIUtils.getSupervisorPort(clusterName));
        UIUtils.addTitleAttribute(model, "Component Summary");
        try {
            String topologyName = Common.topologyIdToName(topology_id);
            model.addAttribute("topologyName", topologyName);
        } catch (InvalidTopologyException e) {
            e.printStackTrace();
        }

        LOG.info("component page show cost:{}ms", System.currentTimeMillis() - start);
        return "component";
    }



}

jstorm-ui/src/main/webapp/WEB-INF/pages/clusters.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="ct" uri="http://jstorm.alibaba.com/jsp/tags" %>
<%--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  --%>

<html>
<head>
    <jsp:include page="layout/_head.jsp"/>
</head>
<body>
<jsp:include page="layout/_header.jsp"/>

<div class="container-fluid">
    <!-- ========================================================== -->
    <!------------------------- clusters summary --------------------->
    <!-- ========================================================== -->
    <h1>Clusters Summary
        <small>clusters:${clusters.size()} nodes:${nodes}</small>
    </h1>
    <table class="table table-bordered table-hover table-striped sortable center"
           data-table="${clusters.size() > PAGE_MAX ? "full" : "sort"}">
        <thead>
        <tr>
            <th>Cluster Name</th>
            <th>Supervisors</th>
            <th>Ports Usage</th>
            <th>Topologies</th>
            <th>Tasks</th>
            <th>Version</th>
            <th>Conf</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach var="c" items="${clusters}" varStatus="index">
            <tr>
                <td><a href="cluster?name=${c.clusterName}">${c.clusterName}</a></td>
                <td>${c.supervisors}</td>
                <td>${c.slotsUsed} / ${c.slotsTotal}</td>
                <td>${c.topologies}</td>
                <td>${c.taskTotal}</td>
                <td>${c.stormVersion}</td>
                <td><a href="conf?name=${c.clusterName}" target="_blank">conf</a></td>
            </tr>
        </c:forEach>
        </tbody>
    </table>

</div>

<jsp:include page="layout/_footer.jsp"/>
</body>
</html>

jstorm-ui/src/main/webapp/WEB-INF/pages/component.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="ct" uri="http://jstorm.alibaba.com/jsp/tags" %>
<%--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  --%>

<html>
<head>
    <jsp:include page="layout/_head.jsp"/>
</head>
<body>
<jsp:include page="layout/_header.jsp"/>

<div class="container-fluid">


    <!-- ========================================================== -->
    <!------------------------- Component Summary --------------------->
    <!-- ========================================================== -->
    <h2>
        Component Summary
        <%--<span id="more-metric" class="glyphicon glyphicon-collapse-down more-metrics" title="Show more metrics info"--%>
        <%--data-toggle="tooltip" data-placement="bottom"></span>--%>
        |
        <span class="window" id="metric">
            Window:
            <a href="component?cluster=${clusterName}&topology=${topologyId}&component=${compName}&win=60"
               class="label ${cls_60}">1 min</a>
            <a href="component?cluster=${clusterName}&topology=${topologyId}&component=${compName}&win=600"
               class="label ${cls_600}">10 min</a>
            <a href="component?cluster=${clusterName}&topology=${topologyId}&component=${compName}&win=7200"
               class="label ${cls_7200}">2 hours</a>
            <a href="component?cluster=${clusterName}&topology=${topologyId}&component=${compName}&win=86400"
               class="label ${cls_86400}">1 day</a>
        </span>
    </h2>

    <table class="table table-bordered table-hover table-striped center">
        <thead>
        <tr>
            <th>Topology</th>
            <th>Component</th>
            <th>Tasks</th>
            <c:forEach var="head" items="${compHead}">
                <th><ct:pretty input="${head}" type="head"/></th>
            </c:forEach>
            <th>Error</th>
        </tr>
        </thead>
        <tbody>
        <c:choose>
            <c:when test="${comp != null}">
                <tr>
                    <td>${topologyName}</td>
                    <td class="text-left" data-order="${comp.type}">
                        <c:choose>
                            <c:when test="${comp.type eq 'bolt'}">
                        <span class="glyphicon glyphicon-flash" title="Bolt" data-toggle="tooltip"
                              data-placement="bottom"></span>
                            </c:when>
                            <c:otherwise>
                        <span class="glyphicon glyphicon-random" title="Spout" data-toggle="tooltip"
                              data-placement="bottom"></span>
                            </c:otherwise>
                        </c:choose>
                            ${comp.componentName}
                        <c:if test="${comp.parentComponent.size() > 0}">
                            <div class="comp-sub hidden">
                                <c:forEach var="parent" items="${comp.parentComponent}">
                                    ${parent}<br/>
                                </c:forEach>
                            </div>
                        </c:if>
                    </td>
                    <td class="middle">${comp.parallel}</td>
                    <c:forEach var="head" items="${compHead}">
                        <td>${comp.metrics.get(head)}
                            <ct:submetric metric="${comp.subMetrics}" parentComp="${comp.parentComponent}"
                                          metricName="${head}" clazz="comp-sub"/>
                        </td>
                    </c:forEach>
                    <td><ct:error e="${comp.errors}"/></td>
                </tr>
            </c:when>
            <c:otherwise>
                <tr class="center">
                    <td colspan="13">
                        <c:choose>
                            <c:when test="${flush != null}">
                                ${flush}
                            </c:when>
                            <c:otherwise>
                                No records found.
                            </c:otherwise>
                        </c:choose>
                    </td>
                </tr>
            </c:otherwise>
        </c:choose>
        </tbody>
    </table>

    <!-- ========================================================== -->
    <!------------------------- Task Stats --------------------->
    <!-- ========================================================== -->
    <h2>Task Stats</h2>
    <table class="table table-bordered table-hover table-striped sortable center"
           data-table="${tasks.size() > PAGE_MAX ? "full" : "sort"}">
        <thead>
        <tr>
            <th>Task Id</th>
            <th>Component</th>
            <th>Type</th>
            <th>Host</th>
            <th>Port</th>
            <th>Uptime</th>
            <th>Status</th>
            <th>Error</th>
            <th>Log</th>
            <th>jstack</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach var="task" items="${tasks}">
            <tr>
                <td>
                    <a href="task?cluster=${clusterName}&topology=${topologyId}&component=${task.component}&id=${task.id}"
                       target="_blank">
                            ${task.id}
                    </a>
                </td>
                <td>${task.component}</td>
                <td>${task.type}</td>
                <td>
                    <a href="supervisor?cluster=${clusterName}&host=${task.host}">
                            ${task.host}</a></td>
                <td>${task.port}</td>
                <td>${task.uptime}</td>
                <td><ct:status status="${task.status}"/></td>
                <td><ct:error e="${task.errors}"/></td>
                <td>
                    <a href="log?cluster=${clusterName}&host=${task.host}&wport=${task.port}&port=${supervisorPort}&tid=${topologyId}"
                       target="_blank">view log</a></td>
                <td>
                    <a href="jstack?cluster=${clusterName}&host=${task.host}&wport=${task.port}&port=${supervisorPort}"
                       target="_blank">view jstack</a>
                </td>
            </tr>
        </c:forEach>

        </tbody>
    </table>
    <!-- ========================================================== -->
    <!------------------------- Task Metrics --------------------->
    <!-- ========================================================== -->
    <h2>Task Metrics
        <%--<span id="more-metrics" class="glyphicon glyphicon-collapse-down more-metrics" title="Show more metrics info"--%>
        <%--data-toggle="tooltip" data-placement="bottom"></span>--%>
    </h2>
    <table class="table table-bordered table-hover table-striped sortable"
           data-table="${taskData.size() > PAGE_MAX ? "full" : "sort"}">
        <thead class="center">
        <tr>
            <th>Task</th>
            <c:forEach var="head" items="${taskHead}">
                <th><ct:pretty input="${head}" type="head"/></th>
            </c:forEach>
        </tr>
        </thead>
        <tbody class="text-right">
        <c:forEach var="t" items="${taskData}">
            <tr>
                <td class="text-center">
                    <a href="task?cluster=${clusterName}&topology=${topologyId}&component=${t.componentName}&id=${t.taskId}"
                       target="_blank">
                            ${t.taskId}</a>
                    <c:if test="${t.parentComponent.size() > 0}">
                        <div class="sub-comp hidden">
                            <c:forEach var="parent" items="${t.parentComponent}">
                                ${parent}<br/>
                            </c:forEach>
                        </div>
                    </c:if>
                </td>
                <c:forEach var="head" items="${taskHead}">
                    <td>${t.metrics.get(head)}
                        <ct:submetric metric="${t.subMetrics}" parentComp="${t.parentComponent}"
                                      metricName="${head}"/>
                    </td>
                </c:forEach>
            </tr>
        </c:forEach>
        </tbody>
    </table>

</div>

<jsp:include page="layout/_footer.jsp"/>
<script>
    $(function () {
        $('[data-toggle="popover"]').popover();
        $('[data-toggle="tooltip"]').tooltip();

        $('#more-metrics').click(function () {
            if ($(this).hasClass('glyphicon-collapse-down')) {
                $('.sub-comp').removeClass('hidden');
                $(this).removeClass('glyphicon-collapse-down');
                $(this).addClass('glyphicon-collapse-up');
                $(this).attr("data-original-title", "Hidden detail metrics info");
            } else {
                $('.sub-comp').addClass('hidden');
                $(this).removeClass('glyphicon-collapse-up');
                $(this).addClass('glyphicon-collapse-down');
                $(this).attr("data-original-title", "Show detail metrics info");
            }
        });

        $('#more-metric').click(function () {
            if ($(this).hasClass('glyphicon-collapse-down')) {
                $('.comp-sub').removeClass('hidden');
                $(this).removeClass('glyphicon-collapse-down');
                $(this).addClass('glyphicon-collapse-up');
                $(this).attr("data-original-title", "Hidden detail metrics info");
            } else {
                $('.comp-sub').addClass('hidden');
                $(this).removeClass('glyphicon-collapse-up');
                $(this).addClass('glyphicon-collapse-down');
                $(this).attr("data-original-title", "Show detail metrics info");
            }
        });

    });

</script>
</body>
</html>